# Generated by Django 5.1.3 on 2024-11-20 09:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagerymodule',
            name='id',
            field=models.IntegerField(default=uuid.UUID('a70c498d-c837-4d26-ad75-039fcfe92f0b'), primary_key=True, serialize=False),
        ),
    ]
