# Generated by Django 5.1.3 on 2024-11-20 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagery', '0002_alter_catagerymodule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagerymodule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
