# Generated by Django 5.1.3 on 2024-11-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagery', '0003_alter_catagerymodule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagerymodule',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
