# Generated by Django 5.1.3 on 2024-11-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagery', '0006_alter_catagerymodule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagerymodule',
            name='Description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='catagerymodule',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
