# Generated by Django 5.1.3 on 2024-11-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catagery", "0007_alter_catagerymodule_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catagerymodule",
            name="Metirial",
            field=models.TextField(blank=True, default=""),
        ),
    ]
